//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MovimientoContable.java
//  @ Date : 28/08/2014
//  @ Author : 
//
//




public class MovimientoContable {
}
